### ISSUE TITLE
徵詢程式使用及修改

### ISSUE THREAD

**Issue by guozhi0302** [tsaiid/vghks-random-duty#50]
蔡醫師您好
我是王國治，陽大畢，即將成為中山附醫外科R1。
因科內有排班需求，搜尋看到您的排班軟體，覺得十分方便又切合醫師排班所需。
但想徵詢您是否同意我修改部分程式碼，以期更適用中山的排版制度使用情形？

我的line: ahbi0302

**Comment by tsaiid** [comment]
歡迎取用，MIT license，你可以自由的 fork，如果有什麼好 idea，也歡迎分享

**Comment by guozhi0302** [comment]
謝謝您。
目前主要考慮多線值班(刀房班、病房班)的安排

**Comment by tsaiid** [comment]
的確這是一個很大的 enhancement，不過目前敝科沒有這個需求，所以我就沒動力去改了
